title: Marius Loeffler
email: hello@example.com
description: >-
  Personal homepage â€” physics, IT transformation, and engineering.
baseurl: ""
url: ""
twitter_username: ""
github_username: MariusLoeffler

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark

header_pages:
  - about.markdown
